# Generated by Django 5.0.2 on 2024-05-20 02:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Doc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250, verbose_name="资料名称")),
                (
                    "file",
                    models.FileField(
                        blank=True, upload_to="Service/", verbose_name="资料文件"
                    ),
                ),
                (
                    "publishDate",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        max_length=20,
                        verbose_name="发布时间",
                    ),
                ),
                ("views", models.PositiveIntegerField(default=0, verbose_name="浏览量")),
            ],
            options={
                "verbose_name": "资料",
                "verbose_name_plural": "资料",
                "ordering": ["-publishDate"],
            },
        ),
    ]
