# Generated by Django 5.0.2 on 2024-04-15 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Major",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enrollment_code",
                    models.CharField(max_length=10, verbose_name="招生代码"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="专业名称")),
                ("level", models.CharField(max_length=20, verbose_name="层次")),
                ("tuition_fee", models.IntegerField(verbose_name="收费标准")),
            ],
            options={
                "verbose_name": "专业信息",
                "verbose_name_plural": "专业信息",
            },
        ),
        migrations.CreateModel(
            name="Admission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exam_number", models.CharField(max_length=20, verbose_name="准考证号")),
                ("name", models.CharField(max_length=100, verbose_name="姓名")),
                (
                    "major",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contactApp.major",
                        verbose_name="录取专业",
                    ),
                ),
            ],
            options={
                "verbose_name": "录取信息",
                "verbose_name_plural": "录取信息",
            },
        ),
    ]
