# Generated by Django 5.0.2 on 2024-05-08 01:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contactApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="招聘岗位")),
                ("description", models.TextField(verbose_name="岗位要求")),
                (
                    "publishDate",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        max_length=20,
                        verbose_name="发布时间",
                    ),
                ),
            ],
            options={
                "verbose_name": "招聘广告",
                "verbose_name_plural": "招聘广告",
                "ordering": ("-publishDate",),
            },
        ),
        migrations.DeleteModel(
            name="Admission",
        ),
        migrations.DeleteModel(
            name="Major",
        ),
    ]
