# Generated by Django 5.0.2 on 2024-05-20 02:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contactApp", "0003_resume"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="birth",
            field=models.DateField(
                default="2024-05-20", max_length=20, verbose_name="出生日期"
            ),
        ),
    ]
