# Generated by Django 5.0.6 on 2024-05-29 01:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contactApp", "0004_alter_resume_birth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="birth",
            field=models.DateField(
                default="2024-05-29", max_length=20, verbose_name="出生日期"
            ),
        ),
    ]
