# Generated by Django 5.0.2 on 2024-04-24 01:34

import DjangoUeditor.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MyNews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="新闻标题")),
                (
                    "description",
                    DjangoUeditor.models.UEditorField(default="", verbose_name="内容"),
                ),
                (
                    "newType",
                    models.CharField(
                        choices=[("公司要闻", "公司要闻"), ("行业新闻", "行业新闻"), ("通知公告", "通知公告")],
                        max_length=50,
                        verbose_name="新闻类型",
                    ),
                ),
                (
                    "publishDate",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        max_length=20,
                        verbose_name="发布时间",
                    ),
                ),
                ("views", models.PositiveIntegerField(default=0, verbose_name="浏览量")),
            ],
            options={
                "verbose_name": "新闻",
                "verbose_name_plural": "新闻",
                "ordering": ["-publishDate"],
            },
        ),
    ]
