# Generated by Django 5.0.6 on 2024-05-29 01:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newsApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mynews",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="news/", verbose_name="展报"
            ),
        ),
    ]
